version: '3'

services:
  gym-app-pg:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gymapp
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
